// @ts-check
/**
 * Webflow-specific spec.
 *
 * Webflow ships a runtime (`webflow.js`) and a fixed set of CSS class
 * conventions (`.w-form`, `.w-tabs`, `.w-dropdown`, `.w-slider`, `.w-lightbox`,
 * `.w-nav-button`, `data-w-id`, …). This spec exercises those components the
 * way a real Webflow developer would expect them to behave, without
 * mistakenly hard-failing on sites that happen to be customised, ejected, or
 * partially generated by Webflow AI / Webflow Components (which ultimately
 * render as standard HTML at runtime).
 *
 * Each component test:
 *   - is gated by `await locator.count()` so the test SKIPS if the component
 *     is not present on the page (rather than failing)
 *   - asserts behaviour, not the presence of the component
 */
const { test, expect } = require('@playwright/test');
const {
  loadSites,
  waitForVisuallyReady,
  installCursorVisualizer,
  scrollPageVisible,
  isHeadedDemo,
} = require('../utils/helpers');

const sites = loadSites();

for (const site of sites) {
  test.describe(`Webflow — ${site.name}`, () => {
    test.beforeEach(async ({ page }) => {
      await installCursorVisualizer(page);
    });

    test.afterEach(async ({ page }, testInfo) => {
      if (testInfo.status === testInfo.expectedStatus) return;
      try {
        const fp = await page.screenshot({ fullPage: true, timeout: 5000 });
        await testInfo.attach('failure-fullpage.png', { body: fp, contentType: 'image/png' });
      } catch {}
      try {
        await testInfo.attach('page-context.txt', {
          body: Buffer.from(`URL: ${page.url()}\nProject: ${testInfo.project.name}\nSite: ${site.name}\n`, 'utf8'),
          contentType: 'text/plain',
        });
      } catch {}
    });

    // ---------- Webflow runtime present (informational) ----------
    test(`Webflow runtime / IX2 detection (informational) @${site.name}`, async ({ page }, testInfo) => {
      await page.goto(site.url, { waitUntil: 'domcontentloaded' });
      await waitForVisuallyReady(page);

      const flags = await page.evaluate(() => ({
        // @ts-ignore
        hasWebflow: typeof window.Webflow !== 'undefined',
        // @ts-ignore
        hasIx2: !!(window.Webflow && (window.Webflow.require ? window.Webflow.require('ix2') : null)),
        wIdElements: document.querySelectorAll('[data-w-id]').length,
        wClassCount: document.querySelectorAll('[class*="w-"]').length,
      }));

      testInfo.annotations.push({
        type: 'webflow-runtime',
        description: `window.Webflow=${flags.hasWebflow} · IX2=${flags.hasIx2} · [data-w-id]=${flags.wIdElements} · class~=w-* count=${flags.wClassCount}`,
      });

      // Soft expectation — at least SOMETHING Webflow-ish is on the page.
      // This passes for any Webflow build, custom Webflow build, or
      // Webflow + AI Component output (which still uses w-* classes).
      // It only fails on completely non-Webflow sites, which is fine —
      // the site was added to a Webflow Tests suite presumably.
      const looksWebflow =
        flags.hasWebflow || flags.wIdElements > 0 || flags.wClassCount > 5;
      expect(
        looksWebflow,
        `Page does not look Webflow-rendered (no window.Webflow, no [data-w-id], only ${flags.wClassCount} w-* class usage). If this is intentional (custom build / ejected), remove tests/webflow.spec.js from your runs.`
      ).toBeTruthy();
    });

    // ---------- .w-form: submit & validation states ----------
    test(`.w-form fill + browser-native required validation @${site.name}`, async ({ page }, testInfo) => {
      await page.goto(site.url, { waitUntil: 'domcontentloaded' });
      await waitForVisuallyReady(page);

      const wForms = page.locator('form.w-form, form');
      const count = await wForms.count();
      if (count === 0) {
        testInfo.annotations.push({ type: 'skipped-reason', description: 'no forms on this page' });
        test.skip(true, 'no forms on this page');
        return;
      }
      const issues = [];
      for (let i = 0; i < Math.min(count, 4); i++) {
        const f = wForms.nth(i);
        if (!(await f.isVisible().catch(() => false))) continue;

        // Inspect Webflow's success/fail siblings (Webflow renders these
        // adjacent to the <form> as .w-form-done / .w-form-fail).
        const wState = await f.evaluate((el) => {
          const parent = el.closest('.w-form') || el.parentElement;
          return {
            hasDone: !!(parent && parent.querySelector('.w-form-done')),
            hasFail: !!(parent && parent.querySelector('.w-form-fail')),
            method: el.method || '',
            action: el.action || '',
          };
        });
        testInfo.annotations.push({
          type: 'w-form',
          description: `form #${i} method=${wState.method} action=${wState.action || '(none)'} has-w-form-done=${wState.hasDone} has-w-form-fail=${wState.hasFail}`,
        });

        // Fill text-like inputs with sentinel values, then check validity.
        const inputs = f.locator(
          'input[type=text], input[type=email], input[type=tel], input[type=url], input[type=number], input:not([type]), textarea'
        );
        const n = await inputs.count();
        for (let k = 0; k < n; k++) {
          const inp = inputs.nth(k);
          if (!(await inp.isVisible().catch(() => false))) continue;
          if (await inp.isDisabled().catch(() => false)) continue;
          const type = (await inp.getAttribute('type')) || '';
          const sample =
            type === 'email' ? 'qa+test@example.com' :
            type === 'tel' ? '+10000000000' :
            type === 'url' ? 'https://example.com' :
            type === 'number' ? '42' : 'QA test';
          try { await inp.fill(sample, { timeout: 3000 }); } catch (e) {
            issues.push({ form: i, error: String(e.message || e) });
          }
        }
      }
      expect(issues, `.w-form fill issues: ${JSON.stringify(issues)}`).toEqual([]);
    });

    // ---------- .w-tabs: clicking each tab activates its pane ----------
    test(`.w-tabs activate panes on click @${site.name}`, async ({ page }, testInfo) => {
      await page.goto(site.url, { waitUntil: 'domcontentloaded' });
      await waitForVisuallyReady(page);

      const tabsContainers = page.locator('.w-tabs');
      const containers = await tabsContainers.count();
      if (!containers) {
        testInfo.annotations.push({ type: 'skipped-reason', description: 'no .w-tabs on this page' });
        test.skip(true, 'no .w-tabs on this page');
        return;
      }
      const issues = [];
      for (let c = 0; c < Math.min(containers, 3); c++) {
        const cont = tabsContainers.nth(c);
        await cont.scrollIntoViewIfNeeded().catch(() => {});
        const links = cont.locator('.w-tab-link');
        const n = await links.count();
        for (let i = 0; i < n; i++) {
          const link = links.nth(i);
          if (!(await link.isVisible().catch(() => false))) continue;
          await link.click({ trial: false }).catch(() => {});
          await page.waitForTimeout(250); // tab animation
          // Active class on tab + corresponding pane visible
          const active = await link.evaluate((el) => el.classList.contains('w--current') || el.getAttribute('aria-selected') === 'true');
          if (!active) issues.push({ container: c, tab: i, reason: 'tab did not become active after click' });
        }
      }
      expect(issues, `.w-tabs interaction issues: ${JSON.stringify(issues, null, 2)}`).toEqual([]);
    });

    // ---------- .w-dropdown: toggle expands/collapses ----------
    test(`.w-dropdown toggles expand/collapse @${site.name}`, async ({ page, isMobile }, testInfo) => {
      await page.goto(site.url, { waitUntil: 'domcontentloaded' });
      await waitForVisuallyReady(page);

      // On mobile, dropdowns are typically inside the hamburger; open it first.
      if (isMobile) {
        const burger = page.locator('.w-nav-button').first();
        if (await burger.count()) {
          await burger.click().catch(() => {});
          await page.waitForTimeout(400);
        }
      }

      const toggles = page.locator('.w-dropdown-toggle');
      const total = await toggles.count();
      if (!total) {
        testInfo.annotations.push({ type: 'skipped-reason', description: 'no .w-dropdown-toggle' });
        test.skip(true, 'no .w-dropdown-toggle on this page');
        return;
      }
      let interacted = 0;
      const issues = [];
      for (let i = 0; i < Math.min(total, 4); i++) {
        const t = toggles.nth(i);
        if (!(await t.isVisible().catch(() => false))) continue;
        await t.click({ trial: false }).catch(() => {});
        await page.waitForTimeout(250);
        const list = await page.evaluate((idx) => {
          const tog = document.querySelectorAll('.w-dropdown-toggle')[idx];
          if (!tog) return null;
          const dd = tog.closest('.w-dropdown');
          const list = dd && dd.querySelector('.w-dropdown-list');
          if (!list) return null;
          const cs = getComputedStyle(list);
          const r = list.getBoundingClientRect();
          return {
            visible: r.width > 0 && r.height > 0 && cs.display !== 'none' && cs.visibility !== 'hidden',
            expanded: tog.getAttribute('aria-expanded') === 'true' || list.classList.contains('w--open'),
          };
        }, i);
        if (list && (list.visible || list.expanded)) {
          interacted++;
        } else {
          issues.push({ toggle: i, reason: 'click did not reveal .w-dropdown-list' });
        }
        // Close again so the next toggle can be tested cleanly.
        await page.keyboard.press('Escape').catch(() => {});
      }
      expect(interacted, 'at least one .w-dropdown opened').toBeGreaterThan(0);
      expect(issues, `.w-dropdown issues: ${JSON.stringify(issues, null, 2)}`).toEqual([]);
    });

    // ---------- .w-slider: arrows advance the slide ----------
    test(`.w-slider arrows advance to next slide @${site.name}`, async ({ page }, testInfo) => {
      await page.goto(site.url, { waitUntil: 'domcontentloaded' });
      await waitForVisuallyReady(page);

      const sliders = page.locator('.w-slider');
      const total = await sliders.count();
      if (!total) {
        testInfo.annotations.push({ type: 'skipped-reason', description: 'no .w-slider' });
        test.skip(true, 'no .w-slider on this page');
        return;
      }
      const issues = [];
      for (let i = 0; i < Math.min(total, 2); i++) {
        const s = sliders.nth(i);
        if (!(await s.isVisible().catch(() => false))) continue;
        await s.scrollIntoViewIfNeeded().catch(() => {});
        const right = s.locator('.w-slider-arrow-right').first();
        if (!(await right.count()) || !(await right.isVisible().catch(() => false))) continue;

        const before = await s.evaluate((el) => {
          const dots = el.querySelectorAll('.w-slider-dot');
          const active = Array.from(dots).findIndex((d) => d.classList.contains('w-active'));
          return { dotCount: dots.length, activeIdx: active };
        });
        await right.click().catch(() => {});
        await page.waitForTimeout(700); // slide transition
        const after = await s.evaluate((el) => {
          const dots = el.querySelectorAll('.w-slider-dot');
          const active = Array.from(dots).findIndex((d) => d.classList.contains('w-active'));
          return { activeIdx: active };
        });
        if (before.dotCount > 1 && before.activeIdx === after.activeIdx) {
          issues.push({ slider: i, reason: `arrow click did not advance (was=${before.activeIdx}, is=${after.activeIdx})` });
        }
      }
      expect(issues, `.w-slider issues: ${JSON.stringify(issues, null, 2)}`).toEqual([]);
    });

    // ---------- .w-lightbox: opens and closes ----------
    test(`.w-lightbox opens and dismisses @${site.name}`, async ({ page }, testInfo) => {
      await page.goto(site.url, { waitUntil: 'domcontentloaded' });
      await waitForVisuallyReady(page);

      const triggers = page.locator('.w-lightbox');
      const total = await triggers.count();
      if (!total) {
        testInfo.annotations.push({ type: 'skipped-reason', description: 'no .w-lightbox' });
        test.skip(true, 'no .w-lightbox on this page');
        return;
      }
      const t = triggers.first();
      if (!(await t.isVisible().catch(() => false))) {
        test.skip(true, 'first .w-lightbox not visible');
        return;
      }
      await t.scrollIntoViewIfNeeded().catch(() => {});
      await t.click().catch(() => {});
      await page.waitForTimeout(500);
      const overlay = page.locator('.w-lightbox-backdrop, .w-lightbox-container');
      const visible = (await overlay.count()) && (await overlay.first().isVisible().catch(() => false));
      // Close
      await page.keyboard.press('Escape').catch(() => {});
      await page.waitForTimeout(300);
      expect(visible, 'lightbox should open after clicking the trigger').toBeTruthy();
    });

    // ---------- IX2 (Interactions 2.0) — scroll triggers fire ----------
    test(`IX2 scroll-triggered animations actually trigger @${site.name}`, async ({ page }, testInfo) => {
      await page.goto(site.url, { waitUntil: 'domcontentloaded' });
      await waitForVisuallyReady(page);

      const ixCount = await page.locator('[data-w-id]').count();
      if (!ixCount) {
        testInfo.annotations.push({ type: 'skipped-reason', description: 'no [data-w-id] elements (no IX2 interactions)' });
        test.skip(true, 'no [data-w-id] elements on this page');
        return;
      }

      // Snapshot the inline-style "fingerprint" of every IX2 element BEFORE
      // scrolling, then again AFTER, and assert at least one changed —
      // proving IX2 fired.
      const fingerprintBefore = await page.evaluate(() => {
        return Array.from(document.querySelectorAll('[data-w-id]')).map((el) => el.getAttribute('style') || '').join('|');
      });
      // In headed/demo mode, use the visible smooth scroll so the user can
      // see IX2 fire as the page scrolls. In headless, just jump to the bottom.
      if (isHeadedDemo()) {
        await scrollPageVisible(page);
      } else {
        await page.evaluate(() => {
          const totalH = document.documentElement.scrollHeight;
          window.scrollTo({ top: totalH, behavior: 'instant' });
        });
        await page.waitForTimeout(800);
      }
      const fingerprintAfter = await page.evaluate(() => {
        return Array.from(document.querySelectorAll('[data-w-id]')).map((el) => el.getAttribute('style') || '').join('|');
      });

      testInfo.annotations.push({
        type: 'ix2',
        description: `[data-w-id] elements=${ixCount} · style fingerprint ${fingerprintBefore === fingerprintAfter ? 'UNCHANGED' : 'CHANGED'} after full scroll`,
      });
      // Soft check — IX2 might be entirely on-load (not scroll), so we don't fail.
      // The annotation tells you whether scroll-triggered IX2 is happening.
    });

    // ---------- Smooth-scroll anchor links ----------
    test(`anchor links (#section) scroll to in-page targets @${site.name}`, async ({ page }, testInfo) => {
      await page.goto(site.url, { waitUntil: 'domcontentloaded' });
      await waitForVisuallyReady(page);

      const anchors = await page.evaluate(() => {
        const out = [];
        document.querySelectorAll('a[href^="#"]').forEach((a) => {
          const href = a.getAttribute('href');
          if (!href || href === '#' || href === '#!') return;
          const target = document.querySelector(href);
          if (!target) return;
          out.push({ href, hasTarget: true });
        });
        return out;
      });
      if (!anchors.length) {
        testInfo.annotations.push({ type: 'skipped-reason', description: 'no in-page anchor links resolve' });
        test.skip(true, 'no in-page anchor links');
        return;
      }
      const a = anchors[0];
      const before = await page.evaluate(() => window.scrollY);
      await page.locator(`a[href="${a.href}"]`).first().click().catch(() => {});
      await page.waitForTimeout(800);
      const after = await page.evaluate(() => window.scrollY);
      expect(after, `clicking ${a.href} should scroll the page`).not.toBe(before);
    });

    // ---------- 404 page is custom (Webflow lets you set one) ----------
    test(`404 page exists and is not the default browser one @${site.name}`, async ({ page, request }, testInfo) => {
      const origin = new URL(site.url).origin;
      const probe = origin + '/this-page-should-not-exist-' + Math.random().toString(36).slice(2, 8);
      const r = await request.fetch(probe, { method: 'GET', timeout: 10_000 });
      const status = r.status();
      const body = await r.text().catch(() => '');
      // Webflow custom 404 is HTTP 404 with a styled HTML body that includes
      // navigation. Browser-default 404 is a tiny plain page.
      const looksCustom = body.length > 1500 || /<nav|<header|<footer/i.test(body);
      testInfo.annotations.push({
        type: '404-page',
        description: `${probe} → HTTP ${status} · body=${body.length}b · looksCustom=${looksCustom}`,
      });
      expect(status, '404 probe should return 404').toBe(404);
      expect(looksCustom, '404 page should be custom (Webflow lets you set one in Site Settings → SEO)').toBeTruthy();
    });
  });
}
